; XIncludeFile #PB_Compiler_File + "i" ;- PBHGEN

Debug GetFilePart(#PB_Compiler_File)

name$ = "C:\pippo.exe"
ext$ = GetExtensionPart(name$)
Debug ext$
Debug Left(name$, Len(name$) - Len(ext$))
;{ "_MyTest.pb" header file.
; ==============================================================================
; Autogenerated by PBHGENX:
; https://github.com/tajmone/pb-xtools
;}==============================================================================

;- PBHGENX v5.43 [https://github.com/tajmone/pb-xtools]
;- '_MyTest.pb' header, autogenerated.
; ==============================================================================
;                                    PBHGENX                                    
; ==============================================================================

; ==============================================================================
;-"_MyTest.pb" header file.
; ------------------------------------------------------------------------------
; Autogenerated by PBHGENX:
; https://github.com/tajmone/pb-xtools
; ==============================================================================


; ==============================================================================
;-"_MyTest.pb" header file.
; Autogenerated by PBHGENX -> https://github.com/tajmone/pb-xtools
; ------------------------------------------------------------------------------
; WARNING: This file is automatically recreated with each save of its main file.
; Any manual changes to this file will be permanently lost!
; ==============================================================================
; recreated
; rewritten
