; ==============================================================================
;- "PBHGENX_Runner.pb" header file.
; Autogenerated by PBHGENX -> https://github.com/tajmone/pb-xtools
; ------------------------------------------------------------------------------
; WARNING: This file is automatically recreated with each save of its main file.
; Any manual changes to this file will be permanently lost!
; ==============================================================================

CompilerIf #PB_Compiler_Module = ""
CompilerEndIf